# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Station.create(name: "新宿")
Station.create(name: "南新宿")
Station.create(name: "参宮橋")
Station.create(name: "代々木八幡")
Station.create(name: "代々木上原")
Station.create(name: "東北沢")
Station.create(name: "下北沢")
Station.create(name: "世田谷代田")
Station.create(name: "梅ヶ丘")
Station.create(name: "豪徳寺")
Station.create(name: "経堂")
Station.create(name: "千歳船橋")
Station.create(name: "祖師ヶ谷大蔵")
Station.create(name: "成城学園前")
Station.create(name: "喜多見")
Station.create(name: "狛江")
Station.create(name: "和泉多摩川")
Station.create(name: "登戸")
Station.create(name: "向ヶ丘遊園")
Station.create(name: "生田")
Station.create(name: "読売ランド前")
Station.create(name: "百合ヶ丘")
Station.create(name: "新百合ヶ丘")
Station.create(name: "柿生")
Station.create(name: "鶴川")
Station.create(name: "玉川学園前")
Station.create(name: "町田")

Category.create(name: "交通（電車・バスなど）")
Category.create(name: "グルメ・買い物")
Category.create(name: "遊び（レジャー施設など）")
Category.create(name: "治安")
Category.create(name: "自然環境")